env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files:
      - ./site/**/*.js
      - ./site/**/*.mjs
rules:
  indent: [error, 2]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, always]
