AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  Repository:
    Type: String
    Description: GitHub Repository URL
  OauthToken:
    Type: String
    Description: GitHub Repository URL
    NoEcho: true
  Branch:
    Type: String
    Description: The name of the branch to deploy off of
  Domain:
    Type: String
    Description: Domain name to host application
    Default: ''


Conditions:
  CreateCustomDomain: !Not [ !Equals [ !Ref Domain, '' ] ]


Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: amplify:*
                Resource: '*'

  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Name: !Sub mbarneyme-${Branch}
      Repository: !Ref Repository
      OauthToken: !Ref OauthToken
      AccessToken: !Ref OauthToken
      CustomRules:
        - Source: </^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|webmanifest|woff2)$)([^.]+$)/>
          Target: /
          Status: '200'

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref Branch
      AppId: !GetAtt AmplifyApp.AppId
      EnableAutoBuild: true
      Stage: PRODUCTION

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Condition: CreateCustomDomain
    Properties:
      DomainName: !Ref Domain
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - BranchName: !GetAtt AmplifyBranch.BranchName
          Prefix: ''
        - BranchName: !GetAtt AmplifyBranch.BranchName
          Prefix: www
