name: release-prod

on:
  workflow_dispatch: {}

env:
  CHANGE_SET_NAME: release-${{ github.run_number }}-${{ github.run_attempt }}
  CHANGE_SET_DESCRIPTION: ${{ github.ref_name }}
  TARGET_ACCOUNT_ID: ${{ secrets.PROD_ACCOUNT_ID }}
  ENVIRONMENT_NAME: prod

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: |
          pip install -r requirements.txt
          npm ci
          npm run lint
  deploy_prod:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://barney.dev
    steps:
      - uses: actions/checkout@v4
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ env.TARGET_ACCOUNT_ID }}:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - name: Deploy
        run: |
          npm ci
          npm run infra:barneydev:deploy
