name: release-qa

on:
  workflow_dispatch: {}
  push:
    tags: '*'

env:
  DEVOPS_ACCOUNT_ID: ${{ secrets.DEVOPS_ACCOUNT_ID }}
  CHANGE_SET_NAME: release-${{ github.run_number }}-${{ github.run_attempt }}
  CHANGE_SET_DESCRIPTION: ${{ github.event.head_commit.message }}
  APPLICATION_NAME: mbarneyme
  TARGET_ACCOUNT_ID: ${{ secrets.QA_ACCOUNT_ID }}
  ENVIRONMENT_NAME: qa
  HOSTED_ZONE_NAME: qa.mbarney.me
  DOMAIN_NAME: qa.mbarney.me

permissions:
  id-token: write
  contents: write
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: |
          make lint
  deploy_qa:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://qa.mbarney.me
    steps:
      - uses: actions/checkout@v4
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ env.TARGET_ACCOUNT_ID }}:role/github-actions
          role-session-name: GitHubActions-${{ github.run_id }}
      - id: create_change_set
        name: Create Change Set
        run: |
          make create-change-set
          export CHANGE_SET_STATUS_REASON="$(cat artifacts/${STACK_NAME}-${CHANGE_SET_NAME}.json | jq -r .StatusReason)"
          if [[ "$CHANGE_SET_STATUS_REASON" == "The submitted information didn't contain changes. Submit different information to create a change set." ]];
          then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          fi;
      - name: Execute Change Set
        if: ${{ steps.create_change_set.outputs.no_changes != 'true' }}
        run: |
          make deploy-change-set
      - name: Deploy site assets
        id: deploy_site
        run: |
          make upload
